# THE UNLOX ACADEMY
## Week 1 — Master Assignment
### Python Fundamentals + NumPy Foundations
**Name:** `Dev Anand Singh`

---
## Section C — Coding Practice
### C1 — Warm-up (Q16–Q20)

**Q16. Swap two numbers WITHOUT using a third variable. Implement 3 different methods: (a) using
arithmetic, (b) using XOR (`^`), (c) using tuple unpacking. Compare which is most Pythonic.**

In [15]:
a, b = 10, 20

# Method (a): Arithmetic
a = a + b
b = a - b
a = a - b
print(f"(a) Arithmetic swap: a={a}, b={b}")

# Method (b): Using XOR
a, b = 10, 20
a = a ^ b  #10^20=30
b = a ^ b  #30^20=10
a = a ^ b  #30^10=20
print(f"(b) XOR swap: a={a}, b={b}")

# Method (c): Tuple unpacking
a, b = 10, 20
a, b = b, a
print(f"(c) Tuple swap: a={a}, b={b}")

# Most Pythonic: (c). One line, readable, no risk of integer overflow (unlike arithmetic).
# XOR is a CS classic but unreadable; arithmetic fails for floats in edge cases.

(a) Arithmetic swap: a=20, b=10
(b) XOR swap: a=20, b=10
(c) Tuple swap: a=20, b=10


**Q17. Swiggy Order Calculator. Take item price and quantity as input. Compute total = price ×
quantity. Add 18% GST. Add ₹40 delivery charge if total (before delivery) is below ₹500, else delivery
is FREE. Print all components separately and final amount in this format:**

```
Subtotal: ₹450.00
GST (18%): ₹81.00
Delivery: ₹40.00
------------------------
Total: ₹571.00
```

In [20]:
price = float(input("Enter item price (₹): "))
quantity = int(input("Enter quantity: "))

subtotal = price * quantity
gst = subtotal * 0.18
if subtotal < 500:
    delivery = 40
else:
    delivery = 0
total = subtotal + gst + delivery

print(f"Subtotal: ₹{subtotal:.2f}")
print(f"GST (18%): ₹{gst:.2f}")
print(f"Delivery: ₹{delivery:.2f}")
print("-" * 24)
print(f"Total: ₹{total:.2f}")

Enter item price (₹): 120
Enter quantity: 3
Subtotal: ₹360.00
GST (18%): ₹64.80
Delivery: ₹40.00
------------------------
Total: ₹464.80


**Q18. Temperature converter. Ask user for a value and unit (C or F). Convert and print result rounded
to 2 decimal places. Handle invalid unit input gracefully (print an error message, do NOT crash).**

In [35]:
try:
    value = float(input("Enter temperature value: "))
    unit = input("Enter unit (C or F): ").strip().upper()

    if unit == "C":
        result = (value * 9 / 5) + 32
        print(f"{value}°C = {result:.2f}°F")
    elif unit == "F":
        result = (value - 32) * 5 / 9
        print(f"{value}°F = {result:.2f}°C")
    else:
        print(f"Error: Invalid unit '{unit}'. Please enter 'C' or 'F'.")
except ValueError:
    print(f"Error: Invalid value. Please enter either an Integer or Floating Value.")

Enter temperature value: 240.5
Enter unit (C or F): c
240.5°C = 464.90°F


**Q19. Take a 4-digit number as input. Print the sum of its digits – WITHOUT converting it to a string.
(Use only integer arithmetic: //, %.)**

In [27]:
number = int(input("Enter a 4-digit number: "))
n = abs(number)
digit_sum = 0

while n > 0:
    digit_sum += n % 10
    n //= 10

print(f"Sum of digits of {number}: {digit_sum}")

Enter a 4-digit number: 2456
Sum of digits of 2456: 17


**Q20. Smart input parser. Take a single input from the user. Detect what type it is – try int first, then
float, else treat as string. Print the value AND its detected type. Example: input "42" → int 42, input
"3.14" → float 3.14, input "hello" → str hello.**

In [37]:
raw = input("Enter a value: ")

try:
    value = int(raw)
    print(f"int {value}")
except ValueError:
    try:
        value = float(raw)
        print(f"float {value}")
    except ValueError:
        print(f"str {raw}")

Enter a value: hello
str hello


### C2 — Conditionals & Logic (Q21–Q25)

**Q21. Indian Income Tax Calculator (New Regime, FY 2024–25). Take annual income as input.
Compute tax using these slabs:**
```
Up to ₹3,00,000 : Nil
₹3,00,001 – ₹7,00,000 : 5%
₹7,00,001 – ₹10,00,000 : 10%
₹10,00,001 – ₹12,00,000 : 15%
₹12,00,001 – ₹15,00,000 : 20%
Above ₹15,00,000 : 30%
```
**Tax must be computed slab-wise, NOT flat. Example: income ₹8,00,000 → 0 on first 3L + 5% on next 4L + 10% on
last 1L = ₹20,000 + ₹10,000 = ₹30,000. Print breakdown clearly**

In [47]:
income = float(input("Enter annual income (₹): "))
slabs = [
    (0,        300000,  0.00),
    (300000,   700000,  0.05),
    (700000,  1000000,  0.10),
    (1000000, 1200000,  0.15),
    (1200000, 1500000,  0.20),
    (1500000, float('inf'), 0.30),
]

total_tax = 0
print("\nTax Breakdown:")
print("-" * 45)

for lower, upper, rate in slabs:
    if income <= lower:
        break
    taxable_in_slab = min(income, upper) - lower
    tax_in_slab = taxable_in_slab * rate
    total_tax += tax_in_slab
    if rate > 0:
        print(f"  ₹{lower:.0f} – ₹{min(income,upper):.0f}  @ {rate*100:.0f}%  = ₹{tax_in_slab:.2f}")

print("-" * 45)
print(f"  Total Tax Payable: ₹{total_tax:.2f}")

Enter annual income (₹): 1200000

Tax Breakdown:
---------------------------------------------
  ₹300000 – ₹700000  @ 5%  = ₹20000.00
  ₹700000 – ₹1000000  @ 10%  = ₹30000.00
  ₹1000000 – ₹1200000  @ 15%  = ₹30000.00
---------------------------------------------
  Total Tax Payable: ₹80000.00


**Q22. Validate Indian PAN card format WITHOUT using regex. Format: AAAAA9999A, first 5 are
uppercase letters, next 4 are digits, last 1 is an uppercase letter. Total length = 10. Take input and
print "Valid PAN" or "Invalid PAN — < reason >" where reason explains exactly what's wrong.**

In [51]:
pan = input("Enter PAN number: ").strip()

valid = True
reason = ""

if len(pan) != 10:
    valid = False
    reason = f"length must be 10, got {len(pan)}"
else:
    for i in range(5):
        if not pan[i].isalpha() or not pan[i].isupper():
            valid = False
            reason = f"character at position {i+1} ('{pan[i]}') must be an uppercase letter"
            break
    if valid:
        for i in range(5, 9):
            if not pan[i].isdigit():
                valid = False
                reason = f"character at position {i+1} ('{pan[i]}') must be a digit"
                break
    if valid:
        if not pan[9].isalpha() or not pan[9].isupper():
            valid = False
            reason = f"last character ('{pan[9]}') must be an uppercase letter"

if valid:
    print("Valid PAN")
else:
    print(f"Invalid PAN — {reason}")

Enter PAN number: RHHPS7140A
Valid PAN


**Q23. Bengaluru BESCOM Electricity Bill (LT-2 Residential). Take units consumed as input. Charges:**
```
0 – 50 units : ₹4.10 per unit
51 – 100 units : ₹5.55 per unit
101 – 200 units : ₹7.10 per unit
Above 200 units : ₹8.15 per unit
```
**Add fixed charge: ₹110. Add 6% government tax on (energy charges + fixed charge). Print itemized bill.**

In [58]:
units = float(input("Enter units consumed: "))
energy_charge = 0
if units <= 50:
    energy_charge = units * 4.10
elif units <= 100:
    energy_charge = (50 * 4.10) + ((units - 50) * 5.55)
elif units <= 200:
    energy_charge = (50 * 4.10) + (50 * 5.55) + ((units - 100) * 7.10)
else:
    energy_charge = (50 * 4.10) + (50 * 5.55) + (100 * 7.10) + ((units - 200) * 8.15)

fixed_charge = 110.00
subtotal = energy_charge + fixed_charge
govt_tax = subtotal * 0.06
total = subtotal + govt_tax

print("\nBESCOM Bill:")
print(f"Units Consumed:     {units} units")
print(f"Energy Charges:     ₹{energy_charge:.2f}")
print(f"Fixed Charge:       ₹{fixed_charge:.2f}")
print(f"Government Tax (6%):₹{govt_tax:.2f}")
print("-" * 35)
print(f"Total Amount Due:   ₹{total:.2f}")

Enter units consumed: 241.2

BESCOM Bill:
Units Consumed:     241.2 units
Energy Charges:     ₹1528.28
Fixed Charge:       ₹110.00
Government Tax (6%):₹98.30
-----------------------------------
Total Amount Due:   ₹1736.58


**Q24. Cricket Strike Rate Classifier. Take runs scored and balls faced. Compute strike rate =
(runs/balls) × 100. Classify:**
```
SR > 150 → Explosive (T20 finisher)
100 < SR ≤ 150 → Aggressive (Top order T20)
75 ≤ SR ≤ 100 → Steady (ODI anchor)
SR < 75 → Defensive (Test match)
```
**Edge case: handle balls = 0 (do not crash, print message instead).**

In [2]:
 runs = int(input("Enter runs scored: "))
balls = int(input("Enter balls faced: "))

if balls == 0:
    print("Cannot compute strike rate: balls faced is 0.")
else:
    sr = (runs / balls) * 100
    print(f"Strike Rate: {sr:.2f}")

    if sr > 150:
        print("Classification: Explosive (T20 finisher)")
    elif sr > 100:
        print("Classification: Aggressive (Top order T20)")
    elif sr >= 75:
        print("Classification: Steady (ODI anchor)")
    else:
        print("Classification: Defensive (Test match)")

Enter runs scored: 50
Enter balls faced: 72
Strike Rate: 69.44
Classification: Defensive (Test match)


**Q25. BMI Calculator (Indian standards). Take weight (kg) and height (cm). Compute BMI = weight /
(height_in_meters)². Classify using Indian (not WHO) BMI categories:**
```
BMI < 18.5 → Underweight
18.5 – 22.9 → Normal (Indian range — narrower than WHO)
23.0 – 24.9 → Overweight
25.0 – 29.9 → Obese Class I
BMI ≥ 30 → Obese Class II
```

In [7]:
weight = float(input("Enter weight (kg): "))
height_cm = float(input("Enter height (cm): "))

height_m = height_cm / 100
bmi = weight / (height_m ** 2)

if bmi < 18.5:
    category = "Underweight"
elif bmi <= 22.9:
    category = "Normal"
elif bmi <= 24.9:
    category = "Overweight"
elif bmi <= 29.9:
    category = "Obese Class I"
else:
    category = "Obese Class II"

print(f"BMI: {bmi:.2f}")
print(f"Category (Indian standards): {category}")

Enter weight (kg): 70
Enter height (cm): 177
BMI: 22.34
Category (Indian standards): Normal


### C3 — Nested Loop Patterns (Q26–Q30)

**Q26. Print this pattern for N = 5:**
```
1
1 2
1 2 3
1 2 3 4
1 2 3 4 5
```

In [8]:
N = int(input("Enter N: "))
for row in range(1, N + 1):
    for col in range(1, row + 1):
        print(col, end=" ")
    print() 

Enter N: 5
1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 


**Q27. Print this number diamond for N = 5 (the digits go up to N in the middle row):**
```
 1
 1 2 1
 1 2 3 2 1
1 2 3 4 3 2 1
1 2 3 4 5 4 3 2 1
1 2 3 4 3 2 1
 1 2 3 2 1
 1 2 1
 1
```

In [12]:
N = int(input("Enter N: "))

for row in range(1, 2 * N):
    count = row if row <= N else 2 * N - row
    spaces = " " * (N - count)
    ascending = " ".join(str(i) for i in range(1, count + 1))
    descending = " ".join(str(i) for i in range(count - 1, 0, -1))
    if descending:
        print(spaces + ascending + " " + descending)
    else:
        print(spaces + ascending)

Enter N: 5
    1
   1 2 1
  1 2 3 2 1
 1 2 3 4 3 2 1
1 2 3 4 5 4 3 2 1
 1 2 3 4 3 2 1
  1 2 3 2 1
   1 2 1
    1


**Q28. Print a hollow square of size N (only the border is '*', inside is blank). For N = 5:**
```
* * * * *
* *
* *
* *
* * * * *
```

In [11]:
N = int(input("Enter N: "))
for row in range(N):
    for col in range(N):
        if row == 0 or row == N - 1 or col == 0 or col == N - 1:
            print("*", end=" ")
        else:
            print(" ", end=" ")
    print()

Enter N: 5
* * * * * 
*       * 
*       * 
*       * 
* * * * * 


**Q29. Print the first 5 rows of Pascal's Triangle:**
```
         1
        1 1
       1 2 1
      1 3 3 1
     1 4 6 4 1

```

In [14]:
N = int(input("Enter N: "))
triangle = []

for i in range(N):
    row = [1] * (i + 1)
    for j in range(1, i):
        row[j] = triangle[i - 1][j - 1] + triangle[i - 1][j]
    triangle.append(row)
width = len(" ".join(str(x) for x in triangle[-1]))
for row in triangle:
    print(" ".join(str(x) for x in row).center(width))

Enter N: 5
    1    
   1 1   
  1 2 1  
 1 3 3 1 
1 4 6 4 1


**Q30. Print this character pattern for N = 5 – letters go up to the N-th alphabet:**
```
A
A B
A B C
A B C D
A B C D E
```

In [15]:
N = int(input("Enter N: "))
for row in range(1, N + 1):
    for col in range(row):
        print(chr(ord('A') + col), end=" ")
    print()

Enter N: 5
A 
A B 
A B C 
A B C D 
A B C D E 


### C4 — Loop Logic (Q31–Q36)

**Q31. Find all Armstrong numbers between 1 and 9999. (An n-digit number is Armstrong if the sum of
its digits each raised to the power n equals the number itself. Example: 153 = 1³ + 5³ + 3³.) Print them
in a clean comma-separated list with a count at the end.**

In [16]:
armstrong_numbers = []

for num in range(1, 10000):
    n_digits = len(str(num))
    temp = num
    digit_power_sum = 0
    while temp > 0:
        digit = temp % 10
        digit_power_sum += digit ** n_digits
        temp //= 10
    if digit_power_sum == num:
        armstrong_numbers.append(num)

print("Armstrong numbers:", ", ".join(str(n) for n in armstrong_numbers))
print(f"Count: {len(armstrong_numbers)}")

Armstrong numbers: 1, 2, 3, 4, 5, 6, 7, 8, 9, 153, 370, 371, 407, 1634, 8208, 9474
Count: 16


**Q32. Take N as input. Print the first N terms of the Fibonacci series. Also compute and print the SUM
of those N terms. Do NOT use recursion. Edge case: N = 0 should print nothing, sum = 0. N = 1 should
print just 0.**

In [18]:
N = int(input("Enter N: "))

if N == 0:
    print("Sum = 0")
else:
    a, b = 0, 1
    fib_list = []
    for _ in range(N):
        fib_list.append(a)
        a, b = b, a + b

    print("Fibonacci:", ", ".join(str(x) for x in fib_list))
    print(f"Sum of {N} terms: {sum(fib_list)}")

Enter N: 5
Fibonacci: 0, 1, 1, 2, 3
Sum of 5 terms: 7


**Q33. Prime check, optimized. Take a number N. Check if it is prime by iterating only up to √N. Then,
print the SUM of all primes between 2 and N (inclusive). Do not use any library.**

In [19]:
def is_prime(n):
    if n < 2:
        return False
    if n == 2:
        return True
    if n % 2 == 0:
        return False
    i = 3
    while i * i <= n:   # only check up to √n
        if n % i == 0:
            return False
        i += 2
    return True

N = int(input("Enter N: "))
print(f"{N} is {'prime' if is_prime(N) else 'not prime'}")

prime_sum = sum(i for i in range(2, N + 1) if is_prime(i))
print(f"Sum of all primes from 2 to {N}: {prime_sum}")

Enter N: 23
23 is prime
Sum of all primes from 2 to 23: 100


**Q34. Take a number as input. Reverse it WITHOUT converting to string. Then check if the original and
reversed are equal (palindrome). Handle negative numbers, they should be considered NOT
palindrome (because of the minus sign). Examples: 121 → palindrome, 123 → not palindrome, -121
→ not palindrome.**

In [20]:
num = int(input("Enter a number: "))

if num < 0:
    print(f"{num} → Not a palindrome (negative numbers never are)")
else:
    temp = num
    reversed_num = 0
    while temp > 0:
        reversed_num = reversed_num * 10 + (temp % 10)
        temp //= 10

    if num == reversed_num:
        print(f"{num} → Palindrome")
    else:
        print(f"{num} reversed = {reversed_num} → Not a palindrome")

Enter a number: 1221
1221 → Palindrome


**Q35. Take two positive integers. Compute their HCF (Highest Common Factor) using Euclidean
algorithm with a `while` loop. Then compute LCM using the relation: HCF × LCM = a × b. Do not use
math.gcd.**

In [21]:
a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
x, y = a, b
while y != 0:
    x, y = y, x % y
hcf = x

lcm = (a * b) // hcf

print(f"HCF({a}, {b}) = {hcf}")
print(f"LCM({a}, {b}) = {lcm}")

Enter first number: 55
Enter second number: 50
HCF(55, 50) = 5
LCM(55, 50) = 550


**Q36. String scanner, single pass. Take a sentence (e.g., a Swiggy review like "Order came on time,
food was hot, packaging 10/10!"). In ONE pass through the string, count: total characters, total
words, vowels (a, e, i, o, u - case-insensitive), consonants, digits, spaces, and special characters. Print
all counts.**

In [22]:
sentence = input("Enter a sentence: ")
vowels_set = set('aeiouAEIOU')

total_chars = 0
total_words = 0
vowel_count = 0
consonant_count = 0
digit_count = 0
space_count = 0
special_count = 0
in_word = False

for ch in sentence:
    total_chars += 1

    if ch == ' ':
        space_count += 1
        in_word = False
    elif ch.isalpha():
        if not in_word:
            total_words += 1
            in_word = True
        if ch in vowels_set:
            vowel_count += 1
        else:
            consonant_count += 1
    elif ch.isdigit():
        digit_count += 1
        in_word = True 
    else:
        special_count += 1
        in_word = False
print(f"Total characters : {total_chars}")
print(f"Total words      : {total_words}")
print(f"Vowels           : {vowel_count}")
print(f"Consonants       : {consonant_count}")
print(f"Digits           : {digit_count}")
print(f"Spaces           : {space_count}")
print(f"Special chars    : {special_count}")

Enter a sentence: Order came on time, food was hot, packaging 10/10!
Total characters : 50
Total words      : 8
Vowels           : 14
Consonants       : 20
Digits           : 4
Spaces           : 8
Special chars    : 4


### C5 — Lists, Tuples, Sets, Dicts (Q37–Q42)

**Q37. Take 10 student marks (out of 100) as input, space-separated on one line, parse with split() and
map(). Without using sort() or sorted(), find: (a) maximum, (b) minimum, (c) average, (d) count of
students above average, (e) the SECOND highest mark.**

In [23]:
raw = input("Enter 10 marks separated by spaces: ")
marks = list(map(int, raw.split()))

max_mark = marks[0]
for m in marks:
    if m > max_mark:
        max_mark = m
        
min_mark = marks[0]
for m in marks:
    if m < min_mark:
        min_mark = m
        
total = 0
for m in marks:
    total += m
average = total / len(marks)

above_avg = 0
for m in marks:
    if m > average:
        above_avg += 1

second_highest = None
for m in marks:
    if m == max_mark:
        continue
    if second_highest is None or m > second_highest:
        second_highest = m

print(f"Maximum:        {max_mark}")
print(f"Minimum:        {min_mark}")
print(f"Average:        {average:.2f}")
print(f"Above average:  {above_avg} students")
print(f"Second highest: {second_highest}")

Enter 10 marks separated by spaces: 90 95 85 75 70 77 72 62 63 82
Maximum:        95
Minimum:        62
Average:        77.10
Above average:  4 students
Second highest: 90


**Q38. Word Frequency Analyzer for Swiggy reviews. Take a review sentence. Find the frequency of
each word (case-insensitive, "Food" and "food" should be counted together). Print words sorted by
frequency in descending order. Also print the MOST frequent word and its count. Use a dict.**

In [24]:
review = input("Enter a Swiggy review: ")
words = review.lower().split()

freq = {}
for word in words:
    clean_word = ""
    for ch in word:
        if ch.isalpha():
            clean_word += ch
    if clean_word:
        freq[clean_word] = freq.get(clean_word, 0) + 1

items = list(freq.items())  
for i in range(len(items)):
    for j in range(i + 1, len(items)):
        if items[j][1] > items[i][1]:
            items[i], items[j] = items[j], items[i]

print("\nWord Frequencies (descending):")
for word, count in items:
    print(f"  {word}: {count}")

print(f"\nMost frequent: '{items[0][0]}' ({items[0][1]} times)")

Enter a Swiggy review: Order came on time, food was hot, packaging 10/10!

Word Frequencies (descending):
  order: 1
  came: 1
  on: 1
  time: 1
  food: 1
  was: 1
  hot: 1
  packaging: 1

Most frequent: 'order' (1 times)


**Q39. Indian States CRUD. Pre-populate a dict with 5 Indian states and their capitals (e.g., Karnataka
→ Bengaluru, Maharashtra → Mumbai). Then build a menu-driven program:**
1. Add a new state-capital pair
2. Update an existing capital
3. Delete a state
4. Search a state (return capital, or 'Not found')
5. Display all states sorted alphabetically
6. Exit


In [25]:
states = {
    "Karnataka": "Bengaluru",
    "Maharashtra": "Mumbai",
    "Tamil Nadu": "Chennai",
    "Delhi": "New Delhi",
    "West Bengal": "Kolkata"
}

while True:
    print("\n1. Add  2. Update  3. Delete  4. Search  5. Display All  6. Exit")
    choice = input("Choice: ").strip()

    if choice == "1":
        state = input("State: ").strip()
        capital = input("Capital: ").strip()
        states[state] = capital
        print(f"Added: {state} → {capital}")

    elif choice == "2":
        state = input("State to update: ").strip()
        if state in states:
            states[state] = input("New capital: ").strip()
            print("Updated.")
        else:
            print("State not found.")

    elif choice == "3":
        state = input("State to delete: ").strip()
        if state in states:
            del states[state]
            print("Deleted.")
        else:
            print("State not found.")

    elif choice == "4":
        state = input("Search state: ").strip()
        print(states.get(state, "Not found"))

    elif choice == "5":
        print("\nAll States (alphabetical):")
        for state in sorted(states):
            print(f"  {state}: {states[state]}")

    elif choice == "6":
        print("Goodbye!")
        break

    else:
        print("Invalid choice.")


1. Add  2. Update  3. Delete  4. Search  5. Display All  6. Exit
Choice: 1
State: Karnartaka
Capital: Bengaluru
Added: Karnartaka → Bengaluru

1. Add  2. Update  3. Delete  4. Search  5. Display All  6. Exit
Choice: 5

All States (alphabetical):
  Delhi: New Delhi
  Karnartaka: Bengaluru
  Karnataka: Bengaluru
  Maharashtra: Mumbai
  Tamil Nadu: Chennai
  West Bengal: Kolkata

1. Add  2. Update  3. Delete  4. Search  5. Display All  6. Exit
Choice: 3
State to delete: Karnartaka
Deleted.

1. Add  2. Update  3. Delete  4. Search  5. Display All  6. Exit
Choice: 1
State: Karnataka
Capital: Bengaluru
Added: Karnataka → Bengaluru

1. Add  2. Update  3. Delete  4. Search  5. Display All  6. Exit
Choice: 5

All States (alphabetical):
  Delhi: New Delhi
  Karnataka: Bengaluru
  Maharashtra: Mumbai
  Tamil Nadu: Chennai
  West Bengal: Kolkata

1. Add  2. Update  3. Delete  4. Search  5. Display All  6. Exit
Choice: 6
Goodbye!


**Q40. Set Operations. Students in Section A know languages = {Python, Java, C++, SQL}. Students in
Section B know = {Java, JavaScript, Python, Go, SQL}. Using ONLY set operations, find:**

(a) Languages known by BOTH sections

(b) Languages known ONLY by Section A

(c) Languages known ONLY by Section B

(d) Total unique languages across both sections

(e) Languages exclusive to one section but not both (symmetric difference)


In [26]:
section_a = {"Python", "Java", "C++", "SQL"}
section_b = {"Java", "JavaScript", "Python", "Go", "SQL"}

print("(a) Both sections know:         ", section_a & section_b)   
print("(b) Only Section A knows:       ", section_a - section_b)   
print("(c) Only Section B knows:       ", section_b - section_a)
print("(d) Total unique languages:     ", section_a | section_b)   
print("(e) Exclusive to one section:   ", section_a ^ section_b)   

(a) Both sections know:          {'Java', 'Python', 'SQL'}
(b) Only Section A knows:        {'C++'}
(c) Only Section B knows:        {'Go', 'JavaScript'}
(d) Total unique languages:      {'SQL', 'JavaScript', 'Java', 'Go', 'Python', 'C++'}
(e) Exclusive to one section:    {'JavaScript', 'C++', 'Go'}


**Q41. TCS stock prices for a week stored as a tuple: `prices = (3845, 3902, 3878, 3955, 4012, 3998,
4055)` (Mon to Sun in ₹). Find: (a) maximum price and which day, (b) minimum price and which day,
(c) average, (d) biggest single-day gain (and between which days), (e) total volatility = sum of
absolute day-to-day price changes.**

In [27]:
prices = (3845, 3902, 3878, 3955, 4012, 3998, 4055)
days = ("Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun")

max_price = prices[0]
max_day = days[0]
for i in range(len(prices)):
    if prices[i] > max_price:
        max_price = prices[i]
        max_day = days[i]

min_price = prices[0]
min_day = days[0]
for i in range(len(prices)):
    if prices[i] < min_price:
        min_price = prices[i]
        min_day = days[i]

avg = sum(prices) / len(prices)

max_gain = prices[1] - prices[0]
gain_from = days[0]
gain_to = days[1]
for i in range(1, len(prices)):
    gain = prices[i] - prices[i - 1]
    if gain > max_gain:
        max_gain = gain
        gain_from = days[i - 1]
        gain_to = days[i]


volatility = 0
for i in range(1, len(prices)):
    volatility += abs(prices[i] - prices[i - 1])

print(f"(a) Max price: ₹{max_price} on {max_day}")
print(f"(b) Min price: ₹{min_price} on {min_day}")
print(f"(c) Average:   ₹{avg:.2f}")
print(f"(d) Biggest gain: ₹{max_gain} ({gain_from} → {gain_to})")
print(f"(e) Total volatility: ₹{volatility}")

(a) Max price: ₹4055 on Sun
(b) Min price: ₹3845 on Mon
(c) Average:   ₹3949.29
(d) Biggest gain: ₹77 (Wed → Thu)
(e) Total volatility: ₹286


**Q42. Given a list of 20 integers (you generate or hardcode them, some duplicates), produce: (a) the
set of unique numbers, (b) the list of numbers appearing more than once, (c) the list of numbers
appearing EXACTLY once. Do this WITHOUT importing Counter or any other library.**

In [28]:
numbers = [4, 7, 2, 9, 4, 1, 7, 3, 2, 8, 5, 7, 6, 1, 9, 3, 10, 4, 6, 5]

freq = {}
for n in numbers:
    freq[n] = freq.get(n, 0) + 1

unique_set = set(numbers)                                     
duplicates = [n for n in freq if freq[n] > 1]                
only_once = [n for n in freq if freq[n] == 1]                

print("(a) Unique numbers:             ", sorted(unique_set))
print("(b) Appear more than once:      ", sorted(duplicates))
print("(c) Appear exactly once:        ", sorted(only_once))

(a) Unique numbers:              [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
(b) Appear more than once:       [1, 2, 3, 4, 5, 6, 7, 9]
(c) Appear exactly once:         [8, 10]


### C6 — Strings (Q43–Q45)

**Q43. Smart Palindrome Checker. Take a sentence as input. Check if it is a palindrome IGNORING:
case, spaces, and all special characters (punctuation). Examples that should return TRUE: "A man, a
plan, a canal: Panama", "Race car", "No 'x' in Nixon". Hint: build a cleaned version of the string first.**

In [30]:
sentence = input("Enter a sentence: ")

cleaned = ""
for ch in sentence:
    if ch.isalnum():
        cleaned += ch.lower()

reversed_cleaned = cleaned[::-1]

if cleaned == reversed_cleaned:
    print(f"'{sentence}' → TRUE (palindrome)")
else:
    print(f"'{sentence}' → FALSE (not a palindrome)")

Enter a sentence: A man, a plan, a canal: Panama
'A man, a plan, a canal: Panama' → TRUE (palindrome)


**Q44. Manual Title Case. Take a sentence (e.g., "hello world from bengaluru"). Capitalize the first
letter of EACH word, but do NOT use .title() or .capitalize(). Use only .upper() / .lower() and string
indexing. Output: "Hello World From Bengaluru".**

In [31]:
sentence = input("Enter a sentence: ")
words = sentence.split()
result_words = []

for word in words:
    if word:
        title_word = word[0].upper() + word[1:].lower()
        result_words.append(title_word)

print(" ".join(result_words))

Enter a sentence: hello world from bengaluru
Hello World From Bengaluru


**Q45. Caesar Cipher Encryptor. Take a message and a shift value N as input. Encrypt by shifting each
letter forward by N positions in the alphabet (wrapping around, Z + 1 = A). Preserve case. Keep digits,
spaces, and special characters UNCHANGED. Example: "Hello, India!" with shift 3 → "Khoor, Lqgld!"**

In [32]:
message = input("Enter message: ")
shift = int(input("Enter shift (N): "))

encrypted = ""
for ch in message:
    if ch.isalpha():
        base = ord('A') if ch.isupper() else ord('a')
        shifted = (ord(ch) - base + shift) % 26
        encrypted += chr(base + shifted)
    else:
        encrypted += ch

print(f"Encrypted: {encrypted}")

Enter message: Hello, India!
Enter shift (N): 3
Encrypted: Khoor, Lqgld!


### C7 — Functions (Q46–Q47)

**Q46. Write a function `calculate_gst(amount, gst_rate=18, gst_inclusive=False)`:**
- If gst_inclusive=False: amount is base, add GST on top
- If gst_inclusive=True: amount already includes GST, extract it
- Return a tuple: (base_amount, gst_amount, total_amount)
- All values rounded to 2 decimals

Test cases:
```
 calculate_gst(1000) → (1000.00, 180.00, 1180.00)
 calculate_gst(1180, gst_inclusive=True) → (1000.00, 180.00, 1180.00)
 calculate_gst(500, gst_rate=5) → (500.00, 25.00, 525.00)
```

In [36]:
def calculate_gst(amount, gst_rate=18, gst_inclusive=False):
    if gst_inclusive:
        base = amount / (1 + gst_rate / 100)
        gst = amount - base
        total = amount
    else:
        base = amount
        gst = amount * gst_rate / 100
        total = base + gst
    return (round(base, 2), round(gst, 2), round(total, 2))
print(calculate_gst(1000))                         
print(calculate_gst(1180, gst_inclusive=True))     
print(calculate_gst(500, gst_rate=5))              

(1000, 180.0, 1180.0)
(1000.0, 180.0, 1180)
(500, 25.0, 525.0)


**Q47. Write a RECURSIVE function `power(base, exp)` that computes base raised to exp, WITHOUT
using the `**` operator and WITHOUT using `pow()`. Handle exp = 0 (return 1) and negative exp
(return 1/power(base, -exp)). Test with: power(2, 10), power(5, 0), power(3, -2).**

In [37]:
def power(base, exp):
    """Compute base^exp recursively."""
    if exp == 0:
        return 1                         
    if exp < 0:
        return 1 / power(base, -exp)     
    return base * power(base, exp - 1)   


print(power(2, 10))
print(power(5, 0))    
print(power(3, -2))   

1024
1
0.1111111111111111


### C8 — NumPy Foundations (Q48–Q50)

**Q48. Identity Matrix Manipulations. Using NumPy: (a) create a 5×5 identity matrix using np.eye(), (b)
multiply every element by 10, (c) transpose it (yes, it looks the same, explain in a comment WHY
transpose of an identity is itself), (d) compute the sum of diagonal elements, (e) compute the sum of
all elements. Print each step.**

In [38]:
import numpy as np

I = np.eye(5)
print("(a) 5×5 Identity Matrix:")
print(I)

I10 = I * 10
print("\n(b) × 10:")
print(I10)

I_T = I10.T
print("\n(c) Transposed:")
print(I_T)

diag_sum = np.sum(np.diag(I))
print(f"\n(d) Sum of diagonal (original I): {diag_sum}")

total_sum = np.sum(I)
print(f"(e) Sum of all elements (original I): {total_sum}") 

(a) 5×5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

(b) × 10:
[[10.  0.  0.  0.  0.]
 [ 0. 10.  0.  0.  0.]
 [ 0.  0. 10.  0.  0.]
 [ 0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0. 10.]]

(c) Transposed:
[[10.  0.  0.  0.  0.]
 [ 0. 10.  0.  0.  0.]
 [ 0.  0. 10.  0.  0.]
 [ 0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0. 10.]]

(d) Sum of diagonal (original I): 5.0
(e) Sum of all elements (original I): 5.0


**Q49. Zomato Weekly Sales Analytics. Create a NumPy array of 7-day Zomato Bengaluru sales (in ₹):**
```
sales = np.array([12000, 18500, 14200, 22100, 19800, 35200, 28400])
 # Mon Tue Wed Thu Fri Sat Sun
```
**Without using loops, compute and print:**

(a) Total weekly sales

(b) Daily average

(c) The day (Mon/Tue/...) with maximum sales

(d) Number of days with sales above the weekly average

(e) Percentage growth from Monday to Sunday

(f) An array of day-on-day % changes (length 6)

In [39]:
import numpy as np

sales = np.array([12000, 18500, 14200, 22100, 19800, 35200, 28400])
day_names = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]

total = np.sum(sales)
print(f"(a) Total weekly sales: ₹{total:,}")

avg = np.mean(sales)
print(f"(b) Daily average:      ₹{avg:,.2f}")

max_idx = np.argmax(sales)
print(f"(c) Best day:           {day_names[max_idx]} (₹{sales[max_idx]:,})")

above_avg_count = np.sum(sales > avg)
print(f"(d) Days above average: {above_avg_count}")

pct_growth = ((sales[-1] - sales[0]) / sales[0]) * 100
print(f"(e) Growth Mon→Sun:     {pct_growth:.2f}%")

day_on_day_pct = ((sales[1:] - sales[:-1]) / sales[:-1]) * 100
print(f"(f) Day-on-day % change: {np.round(day_on_day_pct, 2)}")

(a) Total weekly sales: ₹150,200
(b) Daily average:      ₹21,457.14
(c) Best day:           Sat (₹35,200)
(d) Days above average: 3
(e) Growth Mon→Sun:     136.67%
(f) Day-on-day % change: [ 54.17 -23.24  55.63 -10.41  77.78 -19.32]


**Q50. The Border Pattern Challenge – NO explicit loops. Create a 5×5 NumPy array where the BORDER
is 1 and the INTERIOR is 0. Output should look like:**
```
[[1 1 1 1 1]
[1 0 0 0 1]
[1 0 0 0 1]
[1 0 0 0 1]
[1 1 1 1 1]]
```

In [40]:
import numpy as np

border = np.ones((5, 5), dtype=int) 
border[1:-1, 1:-1] = 0  

print(border)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
